// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RelayData represents the data needed to create a relay
 */
export class RelayData {
    "URL": string;
    "Read": boolean;
    "Write": boolean;
    "Sync": boolean;

    /** Creates a new RelayData instance. */
    constructor($$source: Partial<RelayData> = {}) {
        if (!("URL" in $$source)) {
            this["URL"] = "";
        }
        if (!("Read" in $$source)) {
            this["Read"] = false;
        }
        if (!("Write" in $$source)) {
            this["Write"] = false;
        }
        if (!("Sync" in $$source)) {
            this["Sync"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelayData instance from a string or object.
     */
    static createFrom($$source: any = {}): RelayData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelayData($$parsedSource as Partial<RelayData>);
    }
}
