// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} nsec
 * @param {string} npub
 * @param {boolean} active
 * @returns {Promise<$models.NostrKey> & { cancel(): void }}
 */
export function CreateNostrKey(nsec, npub, active) {
    let $resultPromise = /** @type {any} */($Call.ByID(450605574, nsec, npub, active));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {number} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteNostrKey(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(907990853, id));
    return $resultPromise;
}

/**
 * @param {number} id
 * @returns {Promise<$models.NostrKey> & { cancel(): void }}
 */
export function GetNostrKey(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(3016819188, id));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<$models.NostrKey[]> & { cancel(): void }}
 */
export function ListNostrKeys() {
    let $resultPromise = /** @type {any} */($Call.ByID(2591303287));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {number} id
 * @param {string} nsec
 * @param {string} npub
 * @param {boolean} active
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateNostrKey(id, nsec, npub, active) {
    let $resultPromise = /** @type {any} */($Call.ByID(3751870067, id, nsec, npub, active));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.NostrKey.createFrom;
const $$createType1 = $Create.Array($$createType0);
