// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export function AddNoteToTrash(note: db$0.Note, tags: db$0.Tag[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(36748134, note, tags) as any;
    return $resultPromise;
}

export function CreateNote(title: string, content: string, notebookID: number, statusID: sql$0.NullInt64, publishedAt: sql$0.NullString, eventId: sql$0.NullString, notetype: string, filetype: string): Promise<db$0.Note> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3651584158, title, content, notebookID, statusID, publishedAt, eventId, notetype, filetype) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function DeleteNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1854972521, id) as any;
    return $resultPromise;
}

export function DeleteNoteFromTrash(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1832826689, id) as any;
    return $resultPromise;
}

export function GetNote(id: number): Promise<db$0.Note> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1230348126, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetNoteFromTrash(id: number): Promise<db$0.GetNoteFromTrashRow> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1889602112, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function ListNotes(notebookId: number, tagId: number, limit: number, pageParam: number, orderBy: string, sortDirection: string): Promise<db$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1572240871, notebookId, tagId, limit, pageParam, orderBy, sortDirection) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function ListNotesFromTrash(limit: number, pageParam: number, orderBy: string, sortDirection: string): Promise<db$0.Trash[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3661159223, limit, pageParam, orderBy, sortDirection) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function RestoreNoteFromTrash(noteId: number, title: string, content: string, notebookID: number, statusID: sql$0.NullInt64, createdAt: string, modifiedAt: string, publishedAt: sql$0.NullString, eventId: sql$0.NullString, notetype: string, filetype: string, tagIds: number[]): Promise<db$0.CreateNoteFromTrashRow> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3762311242, noteId, title, content, notebookID, statusID, createdAt, modifiedAt, publishedAt, eventId, notetype, filetype, tagIds) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SearchNotes(searchTerm: string, notebookID: number, tagID: number, limit: number, pageParam: number, orderBy: string, sortDirection: string): Promise<db$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2746264403, searchTerm, notebookID, tagID, limit, pageParam, orderBy, sortDirection) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SearchTrash(searchTerm: string, limit: number, pageParam: number, orderBy: string, sortDirection: string): Promise<db$0.Trash[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3538009948, searchTerm, limit, pageParam, orderBy, sortDirection) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function UpdateNote(id: number, title: string, content: string, notebookID: number, statusID: sql$0.NullInt64, published: boolean, eventId: sql$0.NullString, pinned: boolean, notetype: string, filetype: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(518540175, id, title, content, notebookID, statusID, published, eventId, pinned, notetype, filetype) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = db$0.Note.createFrom;
const $$createType1 = db$0.GetNoteFromTrashRow.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = db$0.Trash.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = db$0.CreateNoteFromTrashRow.createFrom;
