// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} url
 * @param {boolean} read
 * @param {boolean} write
 * @param {boolean} sync
 * @returns {Promise<$models.Relay> & { cancel(): void }}
 */
export function CreateRelay(url, read, write, sync) {
    let $resultPromise = /** @type {any} */($Call.ByID(2564037930, url, read, write, sync));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteRelays() {
    let $resultPromise = /** @type {any} */($Call.ByID(4014153816));
    return $resultPromise;
}

/**
 * @param {number} id
 * @returns {Promise<$models.Relay> & { cancel(): void }}
 */
export function GetRelay(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(2570438932, id));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<$models.Relay[]> & { cancel(): void }}
 */
export function ListRelays() {
    let $resultPromise = /** @type {any} */($Call.ByID(377038031));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {number} id
 * @param {string} url
 * @param {boolean} read
 * @param {boolean} write
 * @param {boolean} sync
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateRelay(id, url, read, write, sync) {
    let $resultPromise = /** @type {any} */($Call.ByID(1832504309, id, url, read, write, sync));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Relay.createFrom;
const $$createType1 = $Create.Array($$createType0);
