// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {Promise<$models.Settings> & { cancel(): void }}
 */
export function GetAllSettings() {
    let $resultPromise = /** @type {any} */($Call.ByID(1346639610));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} key
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetSetting(key) {
    let $resultPromise = /** @type {any} */($Call.ByID(1317242856, key));
    return $resultPromise;
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateSetting(key, value) {
    let $resultPromise = /** @type {any} */($Call.ByID(2612065271, key, value));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
