packages:
  - app
  - blossom
  - docs
  - mcp
  - relay
  - web
  - www
  - packages/*
patchedDependencies:
  "@codemirror/view": patches/@codemirror__view.patch
  "@lezer/markdown": patches/@lezer__markdown.patch
