import type { EditorThemeClasses } from "lexical";

const codeHighlightClasses = {
  atrule: "text-[#C586C0]",
  attr: "text-[#9CDCFE]",
  boolean: "text-[#569CD6]",
  builtin: "text-[#4EC9B0]",
  cdata: "text-[#6A9955]",
  char: "text-[#CE9178]",
  class: "text-[#4EC9B0]",
  "class-name": "text-[#4EC9B0]",
  comment: "text-[#6A9955]",
  constant: "text-[#4FC1FF]",
  deleted: "text-[#CE9178]",
  doctype: "text-[#6A9955]",
  entity: "text-[#569CD6]",
  function: "text-[#DCDCAA]",
  important: "text-[#569CD6]",
  inserted: "text-[#B5CEA8]",
  keyword: "text-[#569CD6]",
  namespace: "text-[#4EC9B0]",
  number: "text-[#B5CEA8]",
  operator: "text-[#D4D4D4]",
  prolog: "text-[#6A9955]",
  property: "text-[#9CDCFE]",
  punctuation: "text-[#D4D4D4]",
  regex: "text-[#D16969]",
  selector: "text-[#D7BA7D]",
  string: "text-[#CE9178]",
  symbol: "text-[#569CD6]",
  tag: "text-[#569CD6]",
  url: "text-[#3794FF]",
  variable: "text-[#9CDCFE]",
  title: "text-[#569CD6] font-bold",
  bold: "font-bold text-[#D4D4D4]",
  italic: "italic text-[#D4D4D4]",
  strike: "line-through",
  "code-snippet": "text-[#CE9178]",
  "code-block": "text-[#CE9178]",
  "code-language": "text-[#4EC9B0]",
  blockquote: "text-[#6A9955]",
  hr: "text-[#6A9955]",
  list: "text-[#569CD6]",
  "url-reference": "text-[#3794FF]",
  table: "text-[#D4D4D4]",
  "table-header": "text-[#569CD6] font-bold",
  "table-header-row": "text-[#569CD6]",
  "table-data": "text-[#D4D4D4]",
  "table-data-rows": "text-[#D4D4D4]",
  "table-line": "text-[#6A9955]",
  "front-matter": "text-[#4EC9B0]",
  "front-matter-block": "text-[#4EC9B0]",
};

const theme: EditorThemeClasses = {
  ltr: "text-left",
  rtl: "text-right",
  paragraph: "last:mb-0 leading-[1.6] tracking-wide mb-1 py-2",
  quote:
    "border-l-4 mb-6 border-primary/30 pl-4 italic text-muted-foreground last:mb-0",
  heading: {
    h1: "text-3xl font-bold tracking-wide mb-2 text-[var(--heading-color)]",
    h2: "text-2xl font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h3: "text-xl font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h4: "text-lg font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h5: "text-base font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h6: "text-sm font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    checklist: "comet-checklist mt-3 border border-transparent",
    ol: "list-decimal ml-6 mb-2",
    ul: "list-disc ml-6 mb-2",
    listitem: "mb-1",
    listitemChecked:
      "comet-check-item comet-check-item--checked line-through text-muted-foreground",
    listitemUnchecked: "comet-check-item",
  },
  link: "inline text-primary no-underline hover:underline cursor-pointer",
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-muted rounded px-1 py-0.5 font-mono text-sm",
  },
  code: "bg-accent/30 rounded-lg p-4 font-mono text-sm block mb-2 overflow-x-auto",
  codeHighlight: codeHighlightClasses,
  image: "",
  hashtag: "bg-accent text-accent-foreground rounded-md px-1.5 py-0.5",
  hr: "mt-3 mb-6 border-t border-border",
  tableScrollableWrapper: "comet-table-wrapper",
  table: "border-separate border-spacing-0 comet-table",
  tableCell: "border-r px-4 border-accent py-2 text-left align-top",
  tableCellHeader:
    "border-r border-accent text-left px-4 py-2 font-bold bg-accent/30",
  tableRow: "",
  tableSelected: "bg-primary/20",
  tableCellSelected: "bg-primary/20",
};

export default theme;
