// Types mirroring the Rust uniffi-exported types.
// These will be auto-generated by uniffi-bindgen-react-native in production.
// This file serves as the type definitions for development.

export type NotebookSummary = {
  id: string;
  name: string;
  noteCount: number;
};

export type NotebookRef = {
  id: string;
  name: string;
};

export type NoteSummary = {
  id: string;
  title: string;
  notebook: NotebookRef | null;
  editedAt: number;
  preview: string;
  searchSnippet: string | null;
  archivedAt: number | null;
  deletedAt: number | null;
  pinnedAt: number | null;
  readonly: boolean;
};

export type LoadedNote = {
  id: string;
  title: string;
  notebook: NotebookRef | null;
  modifiedAt: number;
  markdown: string;
  archivedAt: number | null;
  deletedAt: number | null;
  pinnedAt: number | null;
  readonly: boolean;
  tags: string[];
  nostrDTag: string | null;
  publishedAt: number | null;
  publishedKind: number | null;
};

export type NotePagePayload = {
  notes: NoteSummary[];
  hasMore: boolean;
  nextOffset: number | null;
  totalCount: number;
};

export type ContextualTagsPayload = {
  tags: string[];
};

export type BootstrapPayload = {
  npub: string;
  notebooks: NotebookSummary[];
  selectedNoteId: string | null;
  initialNotes: NotePagePayload;
  initialTags: ContextualTagsPayload;
  archivedCount: number;
  trashedCount: number;
};

export type NoteFilter =
  | 'all'
  | 'today'
  | 'todo'
  | 'archive'
  | 'trash'
  | 'notebook';

export type NoteSortField = 'modifiedAt' | 'createdAt' | 'title';
export type NoteSortDirection = 'newest' | 'oldest';

export type NoteQueryInput = {
  noteFilter: NoteFilter;
  activeNotebookId: string | null;
  searchQuery: string;
  activeTags: string[];
  limit: number;
  offset: number;
  sortField: NoteSortField;
  sortDirection: NoteSortDirection;
};

export type SaveNoteInput = {
  id: string;
  markdown: string;
};

export type ContextualTagsInput = {
  noteFilter: NoteFilter;
  activeNotebookId: string | null;
};

export type SearchResult = {
  id: string;
  title: string;
  notebook: NotebookRef | null;
  preview: string;
  archivedAt: number | null;
};

export type Relay = {
  url: string;
  kind: string;
  createdAt: number;
};

export type SyncState =
  | { type: 'disconnected' }
  | { type: 'needsUnlock' }
  | { type: 'connecting' }
  | { type: 'authenticating' }
  | { type: 'syncing' }
  | { type: 'connected' }
  | { type: 'error'; message: string };

export type SyncInfo = {
  state: SyncState;
  relayUrl: string | null;
  blossomUrl: string | null;
  npub: string | null;
  syncedNotes: number;
  syncedNotebooks: number;
  pendingNotes: number;
  pendingNotebooks: number;
  totalNotes: number;
  checkpoint: number;
  blobsStored: number;
};

export type AccountSummary = {
  publicKey: string;
  npub: string;
  isActive: boolean;
};

export type BlobFetchStatus = 'downloaded' | 'missing' | 'needsUnlock';
