---
rust:
  directory: ./rust
  manifestPath: comet-mobile/Cargo.toml

android:
  directory: ./android
  targets:
    - arm64-v8a
    - armeabi-v7a
    - x86_64
  apiLevel: 24

ios:
  directory: ./ios
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
