import type { EditorThemeClasses } from "lexical";

const codeHighlightClasses = {
  atrule: "text-syntax-atrule",
  attr: "text-syntax-attribute",
  boolean: "text-syntax-keyword",
  builtin: "text-syntax-type",
  cdata: "text-syntax-comment",
  char: "text-syntax-string",
  class: "text-syntax-type",
  "class-name": "text-syntax-type",
  comment: "text-syntax-comment",
  constant: "text-syntax-constant",
  deleted: "text-syntax-string",
  doctype: "text-syntax-comment",
  entity: "text-syntax-keyword",
  function: "text-syntax-function",
  important: "text-syntax-keyword",
  inserted: "text-syntax-number",
  keyword: "text-syntax-keyword",
  namespace: "text-syntax-type",
  number: "text-syntax-number",
  operator: "text-syntax-foreground",
  prolog: "text-syntax-comment",
  property: "text-syntax-attribute",
  punctuation: "text-syntax-foreground",
  regex: "text-syntax-regex",
  selector: "text-syntax-selector",
  string: "text-syntax-string",
  symbol: "text-syntax-keyword",
  tag: "text-syntax-keyword",
  url: "text-syntax-link",
  variable: "text-syntax-attribute",
  title: "text-syntax-keyword font-bold",
  bold: "font-bold text-syntax-foreground",
  italic: "italic text-syntax-foreground",
  strike: "line-through",
  "code-snippet": "text-syntax-string",
  "code-block": "text-syntax-string",
  "code-language": "text-syntax-type",
  blockquote: "text-syntax-comment",
  hr: "text-syntax-comment",
  list: "text-syntax-keyword",
  "url-reference": "text-syntax-link",
  table: "text-syntax-foreground",
  "table-header": "text-syntax-keyword font-bold",
  "table-header-row": "text-syntax-keyword",
  "table-data": "text-syntax-foreground",
  "table-data-rows": "text-syntax-foreground",
  "table-line": "text-syntax-comment",
  "front-matter": "text-syntax-type",
  "front-matter-block": "text-syntax-type",
};

const theme: EditorThemeClasses = {
  ltr: "text-left",
  rtl: "text-right",
  paragraph: "last:mb-0 leading-[1.6] tracking-wide mb-1",
  quote:
    "relative mb-6 pl-4 italic text-muted-foreground last:mb-0 before:absolute before:inset-y-0 before:left-0 before:w-1 before:rounded-full before:bg-blockquote-accent before:content-['']",
  heading: {
    h1: "text-3xl font-bold tracking-wide mb-2 text-[var(--heading-color)]",
    h2: "text-2xl font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h3: "text-xl font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h4: "text-lg font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h5: "text-base font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
    h6: "text-sm font-bold tracking-wide mb-2 mt-3 text-[var(--heading-color)]",
  },
  list: {
    nested: {
      listitem: "comet-list-item--nested",
    },
    checklist: "comet-list comet-list--check",
    ol: "comet-list comet-list--ordered",
    ul: "comet-list comet-list--unordered",
    listitem: "comet-list-item leading-[1.6] tracking-wide mb-1",
    listitemChecked:
      "comet-list-item leading-[1.6] tracking-wide mb-1 comet-list-item--check comet-list-item--check-checked",
    listitemUnchecked:
      "comet-list-item leading-[1.6] tracking-wide mb-1 comet-list-item--check",
  },
  link: "inline text-primary no-underline hover:underline cursor-pointer",
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-muted rounded px-1 py-0.5 font-mono text-sm",
  },
  code: "bg-accent/30 rounded-lg p-4 font-mono text-sm block mb-2 overflow-x-auto",
  codeHighlight: codeHighlightClasses,
  image: "",
  hashtag:
    "bg-accent text-accent-foreground rounded-md px-1.5 py-0.5 cursor-pointer",
  hr: "comet-hr",
  tableScrollableWrapper: "comet-table-wrapper",
  table: "border-separate border-spacing-0 comet-table",
  tableCell: "border-r px-4 border-accent py-2 text-left align-top",
  tableCellHeader:
    "border-r border-accent text-left px-4 py-2 font-bold bg-accent/30",
  tableRow: "",
  tableSelected: "bg-primary/20",
  tableCellSelected: "bg-primary/20",
};

export default theme;
