// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * NullInt64 represents an int64 that may be null.
 * NullInt64 implements the [Scanner] interface so
 * it can be used as a scan destination, similar to [NullString].
 */
export class NullInt64 {
    "Int64": number;

    /**
     * Valid is true if Int64 is not NULL
     */
    "Valid": boolean;

    /** Creates a new NullInt64 instance. */
    constructor($$source: Partial<NullInt64> = {}) {
        if (!("Int64" in $$source)) {
            this["Int64"] = 0;
        }
        if (!("Valid" in $$source)) {
            this["Valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NullInt64 instance from a string or object.
     */
    static createFrom($$source: any = {}): NullInt64 {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NullInt64($$parsedSource as Partial<NullInt64>);
    }
}

/**
 * NullString represents a string that may be null.
 * NullString implements the [Scanner] interface so
 * it can be used as a scan destination:
 * 
 * 	var s NullString
 * 	err := db.QueryRow("SELECT name FROM foo WHERE id=?", id).Scan(&s)
 * 	...
 * 	if s.Valid {
 * 	   // use s.String
 * 	} else {
 * 	   // NULL value
 * 	}
 */
export class NullString {
    "String": string;

    /**
     * Valid is true if String is not NULL
     */
    "Valid": boolean;

    /** Creates a new NullString instance. */
    constructor($$source: Partial<NullString> = {}) {
        if (!("String" in $$source)) {
            this["String"] = "";
        }
        if (!("Valid" in $$source)) {
            this["Valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NullString instance from a string or object.
     */
    static createFrom($$source: any = {}): NullString {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NullString($$parsedSource as Partial<NullString>);
    }
}
