// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export class PaginatedNotes {
    "notes": db$0.Note[];
    "next_offset": number;
    "prev_offset": number;

    /** Creates a new PaginatedNotes instance. */
    constructor($$source: Partial<PaginatedNotes> = {}) {
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }
        if (!("next_offset" in $$source)) {
            this["next_offset"] = 0;
        }
        if (!("prev_offset" in $$source)) {
            this["prev_offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginatedNotes instance from a string or object.
     */
    static createFrom($$source: any = {}): PaginatedNotes {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField0_0($$parsedSource["notes"]);
        }
        return new PaginatedNotes($$parsedSource as Partial<PaginatedNotes>);
    }
}

// Private type creation functions
const $$createType0 = db$0.Note.createFrom;
const $$createType1 = $Create.Array($$createType0);
