// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: note_tags.sql

package db

import (
	"context"
	"database/sql"
)

const addTagToNote = `-- name: AddTagToNote :exec

INSERT INTO note_tags (note_id, tag_id) VALUES (?, ?)
`

type AddTagToNoteParams struct {
	NoteID sql.NullInt64
	TagID  sql.NullInt64
}

// Note-Tag Junction Table Queries
func (q *Queries) AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error {
	_, err := q.db.ExecContext(ctx, addTagToNote, arg.NoteID, arg.TagID)
	return err
}

const getNotesForTag = `-- name: GetNotesForTag :many
SELECT n.id, n.status_id, n.notebook_id, n.content, n.title, n.created_at, n.modified_at, n.published_at, n.event_id
FROM notes n
JOIN note_tags nt ON n.id = nt.note_id
WHERE nt.tag_id = ?
LIMIT ? OFFSET ?
`

type GetNotesForTagParams struct {
	TagID  sql.NullInt64
	Limit  int64
	Offset int64
}

func (q *Queries) GetNotesForTag(ctx context.Context, arg GetNotesForTagParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesForTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.StatusID,
			&i.NotebookID,
			&i.Content,
			&i.Title,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.PublishedAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForNote = `-- name: GetTagsForNote :many
SELECT t.id, t.name, t.color, t.icon, t.created_at
FROM tags t
JOIN note_tags nt ON t.id = nt.tag_id
WHERE nt.note_id = ?
`

func (q *Queries) GetTagsForNote(ctx context.Context, noteID sql.NullInt64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromNote = `-- name: RemoveTagFromNote :exec
DELETE FROM note_tags WHERE note_id = ? AND tag_id = ?
`

type RemoveTagFromNoteParams struct {
	NoteID sql.NullInt64
	TagID  sql.NullInt64
}

func (q *Queries) RemoveTagFromNote(ctx context.Context, arg RemoveTagFromNoteParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromNote, arg.NoteID, arg.TagID)
	return err
}
