import { EditorView } from "@codemirror/view";

import {
  LIST_INDENT_STEP,
  LIST_MARKER_WIDTH,
} from "@/features/editor/extensions/lists/list-types";

export const listTheme = EditorView.theme({
  ".cm-md-list": {
    "--cm-md-list-indent-step": LIST_INDENT_STEP,
    "--cm-md-list-marker-width": LIST_MARKER_WIDTH,
    paddingLeft:
      "calc(var(--indent-level) * var(--cm-md-list-indent-step) + var(--cm-md-list-marker-width)) !important",
    textIndent: "calc(var(--cm-md-list-marker-width) * -1)",
  },
  ".cm-md-list *": {
    textIndent: "0",
  },
  ".cm-line.cm-md-list-child:not(.cm-md-codeblock):not(.cm-md-bq)": {
    paddingLeft: "var(--cm-md-list-child-indent)",
  },
  ".cm-md-list-marker": {
    alignItems: "center",
    color: "var(--primary)",
    display: "inline-flex",
    justifyContent: "center",
    lineHeight: "1",
    minWidth: "var(--cm-md-list-marker-width)",
    position: "relative",
    textAlign: "center",
    verticalAlign: "baseline",
    whiteSpace: "pre",
    zIndex: "0",
  },
  ".cm-md-bullet-marker-source": {
    color: "transparent",
    display: "inline-block",
    letterSpacing: "0.65rem",
    width: "var(--cm-md-list-marker-width)",
    WebkitTextFillColor: "transparent",
  },
  ".cm-md-bullet-marker-source::before": {
    alignItems: "center",
    color: "var(--primary)",
    content: '"•"',
    display: "inline-flex",
    fontSize: "1.45em",
    justifyContent: "center",
    left: "50%",
    lineHeight: "1",
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translate(-50%, -50%)",
    WebkitTextFillColor: "var(--primary)",
  },
  ".cm-md-number-marker-source": {
    color: "transparent",
    display: "inline-block",
    width: "var(--cm-md-list-marker-width)",
    WebkitTextFillColor: "transparent",
  },
  ".cm-md-number-marker-source::before": {
    color: "var(--primary)",
    content: "var(--display-number)",
    fontVariantNumeric: "tabular-nums",
    left: "50%",
    lineHeight: "1",
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translate(-50%, -50%)",
    WebkitTextFillColor: "var(--primary)",
  },
  ".cm-md-task-marker-source": {
    cursor: "text",
    display: "inline-flex",
    justifyContent: "center",
    width: "var(--cm-md-list-marker-width)",
  },
  ".cm-md-task-empty-placeholder": {
    display: "inline",
    font: "inherit",
    lineHeight: "inherit",
    opacity: "0",
    pointerEvents: "none",
    userSelect: "none",
    verticalAlign: "baseline",
  },
  ".cm-md-task-marker-box": {
    backgroundColor: "var(--background)",
    border: "1px solid var(--editor-checkbox-border)",
    borderRadius: "0.22em",
    boxSizing: "border-box",
    cursor: "pointer",
    display: "inline-block",
    height: "1.15em",
    lineHeight: "1",
    position: "relative",
    transform: "translateY(0.24em)",
    width: "1.15em",
  },
  ".cm-md-task-marker-checked .cm-md-task-marker-box": {
    backgroundColor: "transparent",
    borderColor: "var(--muted-foreground)",
  },
  ".cm-md-task-marker-checked .cm-md-task-marker-box::after": {
    borderColor: "var(--muted-foreground)",
    borderStyle: "solid",
    borderWidth: "0 2px 2px 0",
    boxSizing: "border-box",
    content: '""',
    height: "0.58em",
    left: "50%",
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translate(-50%, -64%) rotate(45deg)",
    width: "0.34em",
  },
  ".cm-md-task-list.cm-md-task-checked": {
    color: "var(--muted-foreground)",
  },
  ".cm-md-task-content-checked": {
    textDecoration: "line-through",
    textDecorationColor: "var(--muted-foreground)",
  },
  ".cm-md-task-list.cm-md-task-checked .cm-md-link": {
    color: "var(--muted-foreground)",
  },
});
