/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AdminRouteRouteImport } from "./routes/admin/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as DashboardLoginRouteImport } from "./routes/dashboard.login";
import { Route as AdminUsersRouteImport } from "./routes/admin/users";
import { Route as AdminLoginRouteImport } from "./routes/admin.login";
import { Route as AdminInviteCodesRouteImport } from "./routes/admin/invite-codes";
import { Route as AdminEventsRouteImport } from "./routes/admin/events";
import { Route as AdminConnectionsRouteImport } from "./routes/admin/connections";
import { Route as AdminBlobsRouteImport } from "./routes/admin/blobs";
import { Route as AdminAllowlistRouteImport } from "./routes/admin/allowlist";

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRouteRoute,
} as any);
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminInviteCodesRoute = AdminInviteCodesRouteImport.update({
  id: "/invite-codes",
  path: "/invite-codes",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminConnectionsRoute = AdminConnectionsRouteImport.update({
  id: "/connections",
  path: "/connections",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminBlobsRoute = AdminBlobsRouteImport.update({
  id: "/blobs",
  path: "/blobs",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminAllowlistRoute = AdminAllowlistRouteImport.update({
  id: "/allowlist",
  path: "/allowlist",
  getParentRoute: () => AdminRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/admin/allowlist": typeof AdminAllowlistRoute;
  "/admin/blobs": typeof AdminBlobsRoute;
  "/admin/connections": typeof AdminConnectionsRoute;
  "/admin/events": typeof AdminEventsRoute;
  "/admin/invite-codes": typeof AdminInviteCodesRoute;
  "/admin/login": typeof AdminLoginRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/dashboard/login": typeof DashboardLoginRoute;
  "/admin/": typeof AdminIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin/allowlist": typeof AdminAllowlistRoute;
  "/admin/blobs": typeof AdminBlobsRoute;
  "/admin/connections": typeof AdminConnectionsRoute;
  "/admin/events": typeof AdminEventsRoute;
  "/admin/invite-codes": typeof AdminInviteCodesRoute;
  "/admin/login": typeof AdminLoginRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/dashboard/login": typeof DashboardLoginRoute;
  "/admin": typeof AdminIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/admin/allowlist": typeof AdminAllowlistRoute;
  "/admin/blobs": typeof AdminBlobsRoute;
  "/admin/connections": typeof AdminConnectionsRoute;
  "/admin/events": typeof AdminEventsRoute;
  "/admin/invite-codes": typeof AdminInviteCodesRoute;
  "/admin/login": typeof AdminLoginRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/dashboard/login": typeof DashboardLoginRoute;
  "/admin/": typeof AdminIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/dashboard"
    | "/admin/allowlist"
    | "/admin/blobs"
    | "/admin/connections"
    | "/admin/events"
    | "/admin/invite-codes"
    | "/admin/login"
    | "/admin/users"
    | "/dashboard/login"
    | "/admin/"
    | "/dashboard/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin/allowlist"
    | "/admin/blobs"
    | "/admin/connections"
    | "/admin/events"
    | "/admin/invite-codes"
    | "/admin/login"
    | "/admin/users"
    | "/dashboard/login"
    | "/admin"
    | "/dashboard";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/dashboard"
    | "/admin/allowlist"
    | "/admin/blobs"
    | "/admin/connections"
    | "/admin/events"
    | "/admin/invite-codes"
    | "/admin/login"
    | "/admin/users"
    | "/dashboard/login"
    | "/admin/"
    | "/dashboard/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRouteRoute: typeof AdminRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/admin/": {
      id: "/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/dashboard/login": {
      id: "/dashboard/login";
      path: "/login";
      fullPath: "/dashboard/login";
      preLoaderRoute: typeof DashboardLoginRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/admin/users": {
      id: "/admin/users";
      path: "/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminUsersRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/login": {
      id: "/admin/login";
      path: "/login";
      fullPath: "/admin/login";
      preLoaderRoute: typeof AdminLoginRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/invite-codes": {
      id: "/admin/invite-codes";
      path: "/invite-codes";
      fullPath: "/admin/invite-codes";
      preLoaderRoute: typeof AdminInviteCodesRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/events": {
      id: "/admin/events";
      path: "/events";
      fullPath: "/admin/events";
      preLoaderRoute: typeof AdminEventsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/connections": {
      id: "/admin/connections";
      path: "/connections";
      fullPath: "/admin/connections";
      preLoaderRoute: typeof AdminConnectionsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/blobs": {
      id: "/admin/blobs";
      path: "/blobs";
      fullPath: "/admin/blobs";
      preLoaderRoute: typeof AdminBlobsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/allowlist": {
      id: "/admin/allowlist";
      path: "/allowlist";
      fullPath: "/admin/allowlist";
      preLoaderRoute: typeof AdminAllowlistRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
  }
}

interface AdminRouteRouteChildren {
  AdminAllowlistRoute: typeof AdminAllowlistRoute;
  AdminBlobsRoute: typeof AdminBlobsRoute;
  AdminConnectionsRoute: typeof AdminConnectionsRoute;
  AdminEventsRoute: typeof AdminEventsRoute;
  AdminInviteCodesRoute: typeof AdminInviteCodesRoute;
  AdminLoginRoute: typeof AdminLoginRoute;
  AdminUsersRoute: typeof AdminUsersRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAllowlistRoute: AdminAllowlistRoute,
  AdminBlobsRoute: AdminBlobsRoute,
  AdminConnectionsRoute: AdminConnectionsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminInviteCodesRoute: AdminInviteCodesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardLoginRoute: typeof DashboardLoginRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
