// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemas$0 from "../db/schemas/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as relays$0 from "./relays/models.js";

/**
 * ArchiveNote archives a note by its ID
 */
export function ArchiveNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(902761560, id) as any;
    return $resultPromise;
}

/**
 * CheckNotebookExists checks if a notebook with the given name already exists in the database
 */
export function CheckNotebookExists(name: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(268777487, name) as any;
    return $resultPromise;
}

/**
 * ClearActiveNote deactivates all active notes
 */
export function ClearActiveNote(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2004080249) as any;
    return $resultPromise;
}

/**
 * ClearActiveNotebooks sets all notebooks to not active
 */
export function ClearActiveNotebooks(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3795418685) as any;
    return $resultPromise;
}

/**
 * ClearActiveTags sets the active status of all tags to false
 */
export function ClearActiveTags(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(687238284) as any;
    return $resultPromise;
}

/**
 * CreateNote inserts a new note into the database and returns the created note
 */
export function CreateNote(title: string, content: string): Promise<schemas$0.Note | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3783994422, title, content) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * CreateNotebook inserts a new notebook into the database
 */
export function CreateNotebook(name: string, pinned: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(882431131, name, pinned) as any;
    return $resultPromise;
}

/**
 * CreateRelay inserts a new relay into the database and returns the created relay
 */
export function CreateRelay(url: string, read: boolean, write: boolean, sync: boolean): Promise<schemas$0.Relay | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2667641403, url, read, write, sync) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * CreateTag inserts a new tag into the database
 */
export function CreateTag(name: string, color: string, icon: string, active: boolean, inactive: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2492870674, name, color, icon, active, inactive) as any;
    return $resultPromise;
}

/**
 * CreateTags inserts multiple tags into the database
 */
export function CreateTags(noteId: number, tagList: string[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1231956147, noteId, tagList) as any;
    return $resultPromise;
}

/**
 * CreateUser inserts a new user into the database
 */
export function CreateUser(nsec: string, npub: string, active: boolean): Promise<schemas$0.User | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2530128525, nsec, npub, active) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DeleteNote deletes a note by its ID
 */
export function DeleteNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1337121777, id) as any;
    return $resultPromise;
}

/**
 * DeleteNotebook deletes a notebook by its ID
 */
export function DeleteNotebook(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(790888740, id) as any;
    return $resultPromise;
}

/**
 * DeleteRelay deletes a relay by its ID
 */
export function DeleteRelay(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3660646350, id) as any;
    return $resultPromise;
}

/**
 * DeleteTag deletes a tag by its ID
 */
export function DeleteTag(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1279528063, id) as any;
    return $resultPromise;
}

/**
 * DeleteUser deletes a user by its ID
 */
export function DeleteUser(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3387249414, id) as any;
    return $resultPromise;
}

/**
 * GetActiveNote retrieves the active note from the database
 */
export function GetActiveNote(): Promise<schemas$0.Note | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2175076152) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetActiveNotebook retrieves the active notebook from the database
 */
export function GetActiveNotebook(): Promise<schemas$0.Notebook | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2283957325) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType7($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetActiveUser retrieves the active user from the database
 */
export function GetActiveUser(): Promise<schemas$0.User | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2477491471) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetAllRelays retrieves all relays from the database
 */
export function GetAllRelays(): Promise<(schemas$0.Relay | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2242042095) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType8($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetArchivedNotes retrieves all archived notes from the database
 */
export function GetArchivedNotes(): Promise<schemas$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3503187217) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetNoteByID retrieves a single note by its ID
 */
export function GetNoteByID(id: number): Promise<schemas$0.Note | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2859106818, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetNotebookByID retrieves a single notebook by its ID
 */
export function GetNotebookByID(id: number): Promise<schemas$0.Notebook | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1987921963, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType7($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetNotebooks retrieves all notebooks from the database
 */
export function GetNotebooks(pinned: boolean): Promise<schemas$0.Notebook[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(763701224, pinned) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType10($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetNotes retrieves all notes from the database with specified ordering, limit, offset, search, and trashed filter
 */
export function GetNotes(orderBy: string, orderDirection: string, limit: number, offset: number, search: string, showTrashed: boolean): Promise<schemas$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(961141263, orderBy, orderDirection, limit, offset, search, showTrashed) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetNotesByNotebookID retrieves all notes by a specific notebook ID
 */
export function GetNotesByNotebookID(notebookID: number): Promise<schemas$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(10554070, notebookID) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetPinnedNotes retrieves all pinned notes from the database
 */
export function GetPinnedNotes(): Promise<schemas$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3277905433) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetRelayByID retrieves a relay by its ID
 */
export function GetRelayByID(id: number): Promise<schemas$0.Relay | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1106514443, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetTagByID retrieves a single tag by its ID
 */
export function GetTagByID(id: number): Promise<schemas$0.Tag | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2723008278, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType12($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetTags retrieves all tags from the database
 */
export function GetTags(): Promise<schemas$0.Tag[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3835819395) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType13($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetTagsByNoteID retrieves all tags associated with a specific note ID
 */
export function GetTagsByNoteID(noteID: number): Promise<schemas$0.Tag[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3922355959, noteID) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType13($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetTrashedNotes retrieves all trashed notes from the database
 */
export function GetTrashedNotes(): Promise<schemas$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2170508510) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetUserByID retrieves a single user by its ID
 */
export function GetUserByID(id: number): Promise<schemas$0.User | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2716774129, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * PinNote pins a note by its ID
 */
export function PinNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1626400925, id) as any;
    return $resultPromise;
}

/**
 * RemoveNoteTags removes all tag associations for a given note ID
 */
export function RemoveNoteTags(noteID: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1625995215, noteID) as any;
    return $resultPromise;
}

/**
 * ReplaceRelays removes all existing relays and inserts the new list of relays into the database
 */
export function ReplaceRelays(relayData: relays$0.RelayData[]): Promise<(schemas$0.Relay | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2472126696, relayData) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType8($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * RestoreNote restores a note from the trash by its ID
 */
export function RestoreNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(543428744, id) as any;
    return $resultPromise;
}

/**
 * SearchNotes searches for notes by content
 */
export function SearchNotes(query: string): Promise<schemas$0.Note[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2567554219, query) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SetActiveNote sets the specified note as active and deactivates all other notes
 */
export function SetActiveNote(noteID: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3110951196, noteID) as any;
    return $resultPromise;
}

/**
 * SetNotebookActive sets a notebook to active by its ID
 */
export function SetNotebookActive(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(455909673, id) as any;
    return $resultPromise;
}

/**
 * SetPublishDetails updates the author, identifier, and published_at fields of a note
 */
export function SetPublishDetails(noteID: number, author: string, identifier: string, publishedAt: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1835734245, noteID, author, identifier, publishedAt) as any;
    return $resultPromise;
}

/**
 * SetTagActive sets the active status of a tag to true
 */
export function SetTagActive(tagID: number, active: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3115775920, tagID, active) as any;
    return $resultPromise;
}

/**
 * SetTagInactive sets the active status of a tag to false
 */
export function SetTagInactive(tagID: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2142607883, tagID) as any;
    return $resultPromise;
}

/**
 * TrashNote moves a note to the trash by its ID
 */
export function TrashNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1322424416, id) as any;
    return $resultPromise;
}

/**
 * UnarchiveNote unarchives a note by its ID
 */
export function UnarchiveNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3018250821, id) as any;
    return $resultPromise;
}

/**
 * UnpinNote unpins a note by its ID
 */
export function UnpinNote(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(365380808, id) as any;
    return $resultPromise;
}

/**
 * UpdateNote updates the content and title of an existing note
 */
export function UpdateNote(note: schemas$0.Note): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1594419559, note) as any;
    return $resultPromise;
}

/**
 * UpdateNotebook updates the details of an existing notebook
 */
export function UpdateNotebook(id: number, name: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2776840946, id, name) as any;
    return $resultPromise;
}

/**
 * UpdateRelay updates an existing relay in the database
 */
export function UpdateRelay(relay: schemas$0.Relay): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3000693652, relay) as any;
    return $resultPromise;
}

/**
 * UpdateTag updates the details of an existing tag
 */
export function UpdateTag(id: number, name: string, color: string, icon: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(193443197, id, name, color, icon) as any;
    return $resultPromise;
}

/**
 * UpdateUser updates the details of an existing user
 */
export function UpdateUser(user: schemas$0.User): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1224790596, user) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = schemas$0.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = schemas$0.Relay.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = schemas$0.User.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = schemas$0.Notebook.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType3);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $Create.Array($$createType6);
const $$createType11 = schemas$0.Tag.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType11);
